# Generated by Django 5.0.6 on 2024-07-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasajero', '0002_pasajero_delete_persona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasajero',
            old_name='cuidad',
            new_name='ciudad',
        ),
    ]
