# Generated by Django 5.0.6 on 2024-07-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_vuelos/'),
        ),
    ]
