# Generated by Django 5.0.6 on 2024-07-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_metadatausuarios_biografia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadatausuarios',
            name='biografia',
        ),
    ]
