# Generated by Django 5.0.6 on 2024-07-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_metadatausuarios_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatausuarios',
            name='hobbie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
