# Generated by Django 5.0.6 on 2024-07-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['-fecha']},
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='fecha_envio',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='leido',
        ),
    ]
