# Generated by Django 5.0.6 on 2024-07-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_alter_mensaje_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['-fecha_envio']},
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='fecha',
            new_name='fecha_envio',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
